

VM_ISO_LINK="https://archive.netbsd.org/pub/NetBSD-archive/NetBSD-8.1/images/NetBSD-8.1-amd64.iso"
VM_OS_NAME="netbsd"
VM_OS_TYPE="NetBSD_64"
VM_SSH_PORT=2225

VM_RELEASE=8.1

VM_SHUTDOWN_CMD="/sbin/shutdown -p now"
VM_INSTALL_CMD="/usr/sbin/pkg_add"

VM_RSYNC_PKG="rsync"
VM_SSHFS_PKG=""
VM_PRE_INSTALL_PKGS="tree"

VM_LOGIN_TAG="NetBSD/amd64 (localhost) (console)"

VM_OPTS="conf/netbsd-8.0.opts.txt"
VM_SYNC_METHODS="rsync,scp,sshfs,nfs,tar"
